#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Field definition
#+DATE: <2017-04-14 Fri>
#+AUTHOR: Daniele Santoro
#+EMAIL: dsantoro@fbk.eu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 9.0.5)
  The following document aims at summarizes the metrics exported by Ceilometer and Monasca agent in a FIWARE region, specifying how each field is calculated and which is the pollster providing it. This documents is based on the exported fields taken from [[file:monasca_field_definitions.yaml][monasca_field_definitions.yaml]] and form the [[https://github.com/telefonicaid/fiware-monitoring-parsers/blob/develop/monasca_persister/README.rst][Monasca Persister data points parser]].

  20170424: In the future a similar summary should be done for the values exported by the [[https://github.com/SmartInfrastructures/FIWARELab-monitoringAPI][monitoringAPI]] in order to have a clear mapping between the metrics collected in the region and the related computed/aggregated metrics provided by the monitoringAPI.

* Entity type: 'host'
   /Retrieved by [[file:~/work/repositories/ficore/ceilometer-plugin-fiware/compute_pollster/host.py][host.py]] pollster or via =nova host-describe HOSTNAME= command/
   - compute.node.ram.tot ::
	Total physical memory (in MB) available in the host. Value of =ram_allocation_ratio= not considered.

   - compute.node.ram.now ::
	Sum of the memory (in MB) allocated to instances that run on the host plus the memory allocated to the host itself.
	Could be more than =compute.node.ram.tot= if =ram_allocation_ratio= is > 1.

   - compute.node.ram.max ::
	Sum of the memory (in MB) allocated to instances that run on the host.
	Could be more than =compute.node.ram.tot= if =ram_allocation_ratio= is > 1.

   - compute.node.cpu.tot ::
	Total number of physical CPUs available in the host. Value of =cpu_allocation_ratio= not considered.

   - compute.node.cpu.now ::
	Sum of the virtual CPUs allocated to instances running on the host plus the virtual CPUs allocated to the host itself.
	Could be more than =compute.node.cpu.tot= if =cpu_allocation_ration= is > 1.
   - compute.node.cpu.max ::
	Sum of the virtual CPUs allocated to instances running on the host.
	Could be more than =compute.node.cpu.tot= if =cpu_allocation_ration= is > 1.

   - compute.node.disk.tot ::
       Total physical disk size (in GB) available in the host for store root and ephemeral disks of instances.
       Usually the volume is =/dev/mapper/vm-nova= and mounted on =/va/lib/nova/=.

   - compute.node.disk.now ::
	Sum of the root and ephemeral disk sizes (in GB) allocated to instances that run on the host plus the disk size allocated to the host itself.

   - compute.node.disk.max ::
	Sum of the root and ephemeral disk sizes (in GB) allocated to instances that run on the host.

   /Standard Ceilometer metrics (https://docs.openstack.org/admin-guide/telemetry-measurements.html#openstack-compute)/

   - compute.node.cpu.percent ::
	Compute host CPU utilization in percentage

   /Note:/ _Allocated_ resources means resources booked from instances of a specific tenant. If instances are in =shutdown= state, resources are still allocated.

  Resources:
  - https://docs.openstack.org/admin-guide/common/nova-show-usage-statistics-for-hosts-instances.html
  - https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/4/html/End_User_Guide/usage_statistics.html
* Entity type = 'vm'
  /Standard Ceilometer measurements starting from Kilo/
  - instance :: Existence of instance. Used by FIWARE monitoring to store in metadata and dimensions the following additional instance information:

    /in metadata/
    - name: name if the instance
    - host: resource_id of the host where the instance runs
    - status: status of the instance
    - instance_type: Instance flavor ID
    - image_ref: Instance base image ID
    - properties: catalogue_ge_id

    /in dimensions/
    - user_id: user ID of instance owner
    - project_id: tenant/project ID of instance owner

  - vcpus ::
	Number of virtual CPUs allocated to the instance.
  - cpu_util ::
	Average CPU utilization of the instance in percentage
  - memory ::
	Volume of RAM (in MB) allocated to the instance.
  - memory.usage ::
	Volume of RAM (in MB) used by the instance from the amount of its allocated memory.
  - memory_util ::
	Instance RAM real utilization in percentage.
	Calculated from a Ceilometer transformer in compute host [[file:~/work/repositories/ficore/ceilometer-plugin-fiware/config/compute/etc/ceilometer/pipeline.yaml][pipeline.yaml]] with =100 * memory.usage / memory=.
  - disk.capacity :: The amount of disk (in B) that the instance can see. Consider the device disk tot space.*
  - disk.usage :: The physical size (in B) of the image container on the host. Consider only the real space used by COW.*

  *: This does not consider any other block device attached to the instance but only the instance root disk.
